Ori-Ticket/Ori-Ticket-FE

- src/pages/CategoryPage.jsx
- src/pages/DetailPage.jsx
- src/pages/PaymentPage.jsx
PaymentPage, CategoryPage 레이아웃 작업 진행중입니다.
> Feat: PaymentPage, CategoryPage 레이아웃

- .gitignore
- src/main.jsx
- src/mocks/handlers/postHandler.js
- src/pages/AdminPage.jsx
- src/pages/MainPage.jsx
- src/pages/PostPage.jsx
- src/pages/ProfilePage.jsx
- src/seatSelect.json
- src/store/shoppingCart.jsx
msw를 이용한 Mocking 제어 코드 주석처리 후
PostPage, MainPage 목데이터에서 백엔드API로 교체하여 
전체 리팩토링 작업하였습니다. 
Main.jsx에 RecoilRoot 추가하고 src/store/ 폴더 생성후 
shppingCart.jsx 파일 추가하였습니다.
MainPage ui Card 형태로 리모델링하고 좋아요 버튼도 추가하였습니다.
PostPage에서 아직 이미지 업로드 기능이 서버와 연동이 안되어 주석처리 해놨습니다.
> :white_check_mark: PostPage, MainPage 백엔드 API 연동

- src/components/search/SearchBar.jsx
- src/pages/AdminPage.jsx
- src/pages/MainPage.jsx
- src/pages/ProfileEditPage.jsx
- src/pages/ProfilePage.jsx
- src/recoil/reportDataState.jsx
MainPage: SearchBar 연결 코드 추가
SearchBar: UI 수정 및 검색 키워드 기능 추가 및 검색 기능 구현, Recoil을 이용해 메인페이지의 카드데이터에서 검색
ProfilePage: UI 수정 및 API 연동 예정
AdminPage: UI 수정 및 API 연동
> :white_check_mark: MainPage, SearchBar, AdminPage, ProfilePage 수정

- src/pages/DetailPage.jsx
> DetailPage 작업 외

- src/pages/DetailPage.jsx
> :white_check_mark: DetailPage UI 수정

- src/components/Router.jsx
- src/components/search/SearchBar.jsx
- src/pages/AdminPage.jsx
- src/pages/CategoryPage.jsx
- src/pages/DetailPage.jsx
- src/pages/MainPage.jsx
- src/pages/PostPage.jsx
- src/pages/ProfileEditPage.jsx
- src/pages/ProfilePage.jsx
- src/recoil/reportDataState.jsx
- src/utils/fetchPostsData.jsx
> Dev -> Main 병합

- src/components/ProtectedRoute.jsx
> :white_check_mark: ProtectedRoute 배포 오류

- src/components/search/SearchBar.jsx
- src/pages/PostPage.jsx
- src/pages/login/KakaoRedirect.jsx
- src/utils/fetchPostsData.jsx
http -> httpS 로 모든 요청 교체 작업 진행하였습니다.
> :white_check_mark: 요청 주소 전면 수정

- index.html
- src/components/ProtectedRoute.jsx
- src/components/search/SearchBar.jsx
- src/pages/DetailPage.jsx
- src/pages/PostPage.jsx
- src/pages/ProfilePage.jsx
- src/pages/login/KakaoRedirect.jsx
- src/utils/fetchPostsData.jsx
디테일 페이지에서 신고 사유 하나만 선택되게 코드        
리팩토링하고 신고 버튼 클릭 시 신고 되게 끔 백엔드 API와 연동 완료하였습니다.
> DetailPage 신고버튼 활성화

- src/pages/SignupPage.jsx
- src/pages/login/KakaoRedirect.jsx
http가 아닌, https로 변경했습니다.
(http://13.124.46.138:8080/)주소에서 -> (https://oriticket.link/)로
> :alien: API요청보내는 주소 수정했습니다.(https://oriticket.link/)

- src/pages/SignupPage.jsx
SignupPage(회원정보등록 페이지)에서
import { useRecoilState } from "recoil";  추가
> useRecoilState 추가

- src/pages/login/KakaoRedirect.jsx
```
const response1 = await axios.get(
`https://oriticket.link/members/kakao/login?code=${code}`
);
console.log("인가코드 제대로 보내졌고, response 받음", response1);
const response2 = await axios.post(
"https://oriticket.link/members/signin",
{
email : response1.data.kakao_account.email,
}
);
```
> KakaoRedirect페이지에서 response1.data.kakao_account.email 보내기

- src/pages/ProfilePage.jsx
[ProfilePage]  memberId 7로 가정하고, 회원탈퇴 기능 구현 후 회원탈퇴 api 연동해보았습니다.
> :sparkles: [ProfilePage]  memberId 7로 가정하고, 회원탈퇴 기능 구현 후 회원탈퇴 api 연동

- src/pages/ProfilePage.jsx
> :bug: 회원탈퇴 기능에서 api 주소 수정

- src/pages/ProfilePage.jsx
`https://oriticket.link/members/withdraw/${memberId}`
> 회원탈퇴 axios.delete 요청 시, RequestParam형식이 아닌 PathVariable형식으로 전송

- src/pages/ProfilePage.jsx
회원탈퇴기능 api 연동 성공 확인했습니다.
다시 memberId 1값으로 원상복구했습니다. @gxvelxx
> :white_check_mark: 회원탈퇴기능 api 연동 확인 후, 다시 memberId 1값으로 원상복구했습니다.

- .gitignore
- package-lock.json
- package.json
- src/pages/CategoryPage.jsx
- src/pages/ChatPage.jsx
- src/pages/DetailPage.jsx
- src/pages/PaymentPage.jsx
- src/pages/PostPage.jsx
- src/pages/ProfilePage.jsx
- src/pages/SignupPage.jsx
- src/pages/login/KakaoRedirect.jsx
- src/recoil/emailState.jsx
- vercel.json
PostPage 오류 수정 하였고, DetailPage 결제창에 티켓 정보가 연동되도록 코드 수정하였습니다.
> :ambulance: PostPage, DetailPage 오류 수정 및 보완

- src/pages/PostPage.jsx
> :pencil2: PostPage UI 수정

- src/pages/DetailPage.jsx
- src/pages/PostPage.jsx
> PostPage UI수정

- src/pages/ChatlistPage.jsx
> :pencil2: ChatListPage 수정

- src/pages/ChatlistPage.jsx
- src/pages/PostPage.jsx
> ChatListPage 수정

- src/pages/DetailPage.jsx
> :bug: 신고기능 오류 수정
